Resources:
  ## Create the VPC here
  SampleVPC:
    Type: "AWS::EC2::VPC"
    Properties:
      CidrBlock: "10.1.0.0/16"
      EnableDnsHostnames: True
      EnableDnsSupport: True
      InstanceTenancy: "default"
      Tags:
        - Key: "Name" 
          Value: "sample-vpc"
  # Creates a simple security group
  SampleSecurityGroup:
     Type: "AWS::EC2::SecurityGroup"
     Properties:
       GroupDescription: "Allow SSH access"
       GroupName: "SampleSecurityGroup"
       VpcId: 
       # This is literal magic. 'Ref' is an intrinsic function
       # that will populate the values form a logical resource, in this
       # case the 'SampleVPC' described above. Somehow, the Cloudformation
       # API is able to extract the VPC ID out of this. Too much magic
       # if you ask me.
         Ref: "SampleVPC"
       SecurityGroupIngress:
         - CidrIp: "0.0.0.0/0"
           FromPort: 22
           ToPort: 22
           IpProtocol: "tcp"
       SecurityGroupEgress:
         - IpProtocol: "-1"
           FromPort: 0
           ToPort: 0
           CidrIp: "0.0.0.0/0"
  # SampleInternetGateway:
  #   Type: "AWS::EC2:InternetGateway"
  # SampleSubnet:
  #   Type: "AWS::EC2:Subnet"
  # SampleRouteTable:
  #   Type: "AWS::EC2::RouteTable"
  # SampleRoute:
  #   Type: "AWS::EC2::Route"
  # SampleSubnetRouteTableAssoc:
  #   Type: "AWS::EC2::SubnetRouteTableSAssociation"
  # SampleEC2Instance:
  #   Type:
